### ISSUE TITLE
Comments

### ISSUE THREAD

**Issue by frajen** [galaxyraver/galaxyraver#16]
test

Pricing: Ticket links are usually separate from the Facebook event link. Possible to parse ticket price from ticket links and/or FB event page? Use ticket link if possible (standard ticket forms, eventbrite/flavor.us/eventfly whatever)

How to verify genre tags? Extract links to external artist pages, need human verification of styles - soundcloud tagging can be useful but at worst case confusing/irrelevant (e.g. "#flumestep" is not really a recognized genre)

Tie event locations to an address and/or venue link

If "Hosts" parsing is viable, also tie to external link

**Comment by alexmingoia** [comment]
Closing this because I've created separate threads for all these points:
- Host links #17
- Ticket links #19 
- Location links #18 
- Genre verification #20
- Prices #21
